# Generated by Django 3.2.20 on 2023-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='путь_к_изображению_по_умолчанию.png', upload_to='avatars/'),
        ),
    ]
